repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=.pylintrc", # Link to your config file
        ]
